services:

  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ecommerce-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"

volumes:
  mysql_data: